train:
	gcc -O3 -w -o threes_train threes_train.c
train_p:
	gcc -O3 -w -o threes_train threes_train_parallel.c -fopenmp
train_pms:
	gcc -O3 -w -o threes_train_ms threes_train_parallel_multi_stage.c -fopenmp
play:
	gcc -O3 -w -o threes_play threes_play.c
play_p:
	gcc -O3 -w -o threes_play threes_play.c -fopenmp
play_MS:
	gcc -O3 -w -o threes_play_MS threes_play_MS.c 
play_MSV:
	gcc -O3 -w -o threes_play_MS_V threes_play_MS_V.c 
test:
	gcc -O3 -w -o test test.c
pj5:
	gcc -O3 -w -o pj5 threes_play_PJ5.c
pj6:
	gcc -O3 -w -o pj6 threes_play_PJ6.c